#!/bin/bash
# LIGHTNING-KERNEL-BUILD

# Variables
DIR="$(pwd)"

PARENT_DIR="$(pwd)"

echo "Cloning dependencies"

git clone --depth=1 --branch stock https://github.com/kevdes/samsung_x110 samsung
cd samsung 
git clone --depth=1 --branch android-11.0.0_r48 https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 aarch64-linux-android-4.9
#git clone --depth=1  https://github.com/prorooter007/android_prebuilts_clang_host_linux-x86_clang-6877366 clang
#git clone --depth=1  https://git.codelinaro.org/clo/la/kernelplatform/prebuilts-master/clang/host/linux-x86.git clang
git clone --depth=1  https://github.com/kdrag0n/proton-clang.git clang
git clone --depth=1 https://github.com/osm0sis/AnyKernel3 AnyKernel3
echo "Done"
KERNEL_DIR=/root/project/predator/samsung/kernel-5.10
#OUT_DIR="${KERNEL_DIR}/out"
REPACK_DIR="${PARENT_DIR}/AnyKernel3"
IMAGE="${KERNEL_DIR}/arch/arm64/boot/Image"
BRANCH="$(git rev-parse --abbrev-ref HEAD)"


#export PLATFORM_VERSION=11
export ANDROID_MAJOR_VERSION=r
export CROSS_COMPILE="$(pwd)/aarch64-linux-android-4.9/bin/aarch64-linux-android-"
export CLANG_TRIPLE="$(pwd)/clang/bin/aarch64-linux-gnu-"
export ARCH=arm64
#export SEC_BUILD_CONF_VENDOR_BUILD_OS=13
export LINUX_GCC_CROSS_COMPILE_PREBUILTS_BIN="$(pwd)/aarch64-linux-android-4.9/bin"
export CLANG_PREBUILT_BIN="$(pwd)/clang/bin"
export PATH=$LINUX_GCC_CROSS_COMPILE_PREBUILTS_BIN:$CLANG_PREBUILT_BIN:$PATH
export LLVM=1
#KERNEL_MAKE_ENV="LOCALVERSION=-Lightning-V2.5"

# Color
ON_BLUE=`echo -e "\033[44m"`	# On Blue
BRED=`echo -e "\033[1;31m"`	# Bold Red
BBLUE=`echo -e "\033[1;34m"`	# Bold Blue
BGREEN=`echo -e "\033[1;32m"`	# Bold Green
UNDER_LINE=`echo -e "\e[4m"`	# Text Under Line
STD=`echo -e "\033[0m"`		# Text Clear

cd ${KERNEL_DIR}

build_kernel(){  
  echo "${BGREEN}***** Compiling kernel *****${STD}"  
  #[ ! -d "$OUT_DIR" ] && mkdir $OUT_DIR
  #python scripts/gen_build_config.py --kernel-defconfig gta9wifi_00_defconfig --kernel-defconfig-overlays "entry_level.config ot11.config" -m user -o out/build.config

  #cd kernel-5.10
  python scripts/gen_build_config.py --kernel-defconfig gta9wifi_00_defconfig --kernel-defconfig-overlays "entry_level.config ot11.config ot11_wifi.config wifionly.config" -m user -o ../out/target/product/gta9wifi/obj/KERNEL_OBJ/build.config

  export ARCH=arm64
  export CROSS_COMPILE="aarch64-linux-gnu-"
  export CROSS_COMPILE_COMPAT="arm-linux-gnueabi-"
  export OUT_DIR="../out/target/product/gta9wifi/obj/KERNEL_OBJ"
  export DIST_DIR="../out/target/product/gta9wifi/obj/KERNEL_OBJ"
  export BUILD_CONFIG="../out/target/product/gta9wifi/obj/KERNEL_OBJ/build.config"
  #cd ../kernel
  #./build/build.sh

  make LLVM=1 LLVM_IAS=1 DEPMOD=depmod DTC=dtc O=/root/project/predator/samsung/out/target/product/gta9wifi/obj/KERNEL_OBJ/kernel-5.10 gki_defconfig ../out/target/product/gta9wifi/obj/KERNEL_OBJ/gta9wifi_00.config entry_level.config ot11.config ot11_wifi.config wifionly.config
}

gsi_kernel(){
  echo "${BGREEN}***** Apply GSI patch *****${STD}"

  cd $KERNEL_DIR
  git apply gsi-commits.patch
}

#ls -la $(pwd)/kernel

#./build_kernel.sh


build_kernel

#gsi_kernel

#build_kernel

